services:
  postgres:
    image: postgres:18.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: former
    volumes:
      - postgres-data:/var/lib/postgresql
    container_name: former-postgres

  server:
    image: former-backend
    build: ./former-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/former
    volumes:
      - ./former-backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: former-backend
    depends_on:
      - postgres

  app:
    image: former-frontend
    build:
      context: .
      dockerfile: ./former-frontend/Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./former-frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: former-frontend

volumes:
  postgres-data: