name: Test and Deploy

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    backend-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./former-backend
        steps:
            -   name: Checkout repository for backend testing
                uses: actions/checkout@v6

            -   name: Setup Node.js for backend
                uses: actions/setup-node@v6

            -   name: Install backend dependencies
                run: npm ci

            -   name: Run backend lint
                run: npm run lint

            -   name: Run backend tests
                run: npm run test

    frontend-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./former-frontend
        steps:
            -   name: Checkout repository for frontend testing
                uses: actions/checkout@v6

            -   name: Setup Node.js for frontend
                uses: actions/setup-node@v6

            -   name: Install frontend dependencies
                run: npm ci

            -   name: Run frontend lint
                run: npm run lint

            -   name: Run frontend tests
                run: npm run test

    backend-deploy:
        needs: backend-test
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./former-backend
        steps:
            -   name: Checkout repository for backend deployment
                uses: actions/checkout@v4

            -   name: Install Heroku CLI for backend
                run: curl https://cli-assets.heroku.com/install.sh | sh

            -   name: Deploy backend to Heroku
                uses: akhileshns/heroku-deploy@v3.15.15
                with:
                    heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                    heroku_app_name: ${{ vars.HEROKU_BACKEND_APP }}
                    heroku_email: ${{ secrets.HEROKU_EMAIL }}

    frontend-deploy:
        needs: frontend-test
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./former-frontend
        steps:
            -   name: Checkout repository for frontend deployment
                uses: actions/checkout@v4

            -   name: Install Heroku CLI for frontend
                run: curl https://cli-assets.heroku.com/install.sh | sh

            -   name: Deploy frontend to Heroku
                uses: akhileshns/heroku-deploy@v3.15.15
                with:
                    heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                    heroku_app_name: ${{ vars.HEROKU_FRONTEND_APP }}
                    heroku_email: ${{ secrets.HEROKU_EMAIL }}