name: Periodic health check
on:
    workflow_dispatch:
    schedule:
        -   cron: '0 0 1 * *'

jobs:
    health_check:
        runs-on: ubuntu-latest
        steps:
            -   name: Check health link
                uses: jtalk/url-health-check-action@v5
                with:
                    url: https://former.hussainmayoof.com|https://former-api.hussainmayoof.com/api/posts
                    max-attempts: 3
                    retry-delay: 15s